[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dora-openarm-ros2"
version = "0.2.0"
authors = [{name = "Enactic, Inc."}]
description = "dora ros2 converter for openarm"
license = {text = "Apache-2.0"}
maintainers = [{name = "Enactic, Inc."}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "daqp==0.7.2",
    "dora-rs==0.5.0",
    "dora-rs-cli==0.5.0",
    "numpy",
    "opencv-python>=4.13.0.92",
    "pyarrow",
]

[project.scripts]
openarm-dora-ros2 = "dora_ros2_bridge.main:main"
openarm-ros2-dora = "ros2_dora_bridge.main:main"

[tool.setuptools]
package-dir = {"" = "node"}

[tool.setuptools.packages.find]
where = ["node"]
