hand:
  kinematic:
    x: 0.0
    y: -0.0205
    z: -0.5585
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

leftfinger:
  kinematic:
    x: 0.0
    y: 0.0775
    z: -0.673001
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

rightfinger:
  kinematic:
    x: 0.0
    y: 0.0775  
    z: -0.673001
    roll: 0.0
    pitch: 0.0
    yaw: 0.0