nodes:
  - id: tick   # ── 250 Hz tick ───────────────────────────────────────────────
    build: pip install git+https://github.com/enactic/dora-openarm-quitter
    path: dora-openarm-quitter
    inputs:
      tick: dora/timer/millis/4
    outputs:
      - tick

  - id: tick-camera
    build: pip install git+https://github.com/enactic/dora-openarm-quitter
    path: dora-openarm-quitter
    inputs:
      tick: dora/timer/millis/33
    outputs:
      - tick

  - id: dummy-leader
    path: ../node/dummy-leader.py
    inputs:
      tick: tick/tick
    outputs:
      - left_position
      - right_position
      - status

  - id: dummy-camera
    path: ../node/dummy-camera.py
    outputs:
      - image

  - id: dora-to-ros2
    build: pip install -e ..
    path: openarm-dora-ros2
    inputs:
      left_position: dummy-leader/left_position
      right_position: dummy-leader/right_position
      camera_image: dummy-camera/image